apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ci-dashboard
  labels:
    app: ci-dashboard
    paas.redhat.com/appcode: ISVD-001
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ci-dashboard:latest
  source:
    type: Git
    git:
      uri: https://github.com/medik8s/ci-dashboard.git
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
